name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    outputs:
      segments: ${{ steps.get-segments.outputs.segments }}
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Cache files for download
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Run download script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWt0cGJtYzVPRGd4SWl3aVVrVlFUeUk2SW5WeVltRnVMVzlqZEc4dGMzVmpZMjkwWVhOb0lpd2lWRWRmUVZCSlgwbEVJam9pTVRZMU5EWXlOekFpTENKVVIxOUJVRWxmU0VGVFNDSTZJakZsTVdWbU1XSmlZalpsT0dNMlltTTVNREF5TURkallUVmhNVEZqWmpaaUlpd2lWRWRmUWs5VVgxUlBTMFZPSWpvaU5USTRNamszTkRjMk5UcEJRVWRJVG1wQ1EzRlNlWFo0WjFWVE9XOTVORWhVUjBOME5VSkRhbk5rTFVwaWN5SXNJa1pKVEVVaU9qUXdNemdzSWtaSlRFVmZUa0ZOUlNJNklsc2dRa3hESUYwZ0lGTXhSVFlnVkc5cmVXOGdWbWxqWlM1dGEzWWlMQ0pKUkNJNklsUnZhMTg1TURFMk16MDFQWFIySWl3aVEwMUVJam9pV20xYWRHTkhWbTVKUXpGd1NVaDBjR0pzT1cxaFYzaHNabE5CZEZwdGJITmtSMVo1V0RKT2RtSllRbk5hV0dkblNXMVNlVmxZWkRCYVdHZ3dVRmRhZG1KdVVtMWhWM2hzVUZkbmVFeHVVakJhYW5Bd1dsaG9NRkJUWTJkV1JXTm5URk5DUVZsdGVERmFWMDVvWVRKV1ptSnRWakJrTWpsNVlYbEJiazl0V25aaWJsSnFZako0ZG1OcU1UTmhSMnd3V2xSd2JXSXlOVEJqTW13MldsUXdlVTVFY0RSUVZFVjNUMjVyT1UxVVFXbEpRekYwV1ZoQlowMURRWFJpVjFZd1dWZFNhR1JIUlRaamVuQm9TVWhTY0dSSGVHeFFVMHBWVW5wdloxRkhTbk5rVjFacVdWZDBiRmd5Tld4a1NHUjJZMjF6YVVsRE1YUmFXRkpvV2tkR01GbFVjSHBQYmsxblpFZHNNR0pIVlRsSmJGSklUMmxDUVZsdGVERmFWMDVvWVRKV1ptSnRWakJrTWpsNVlYbEJhVWxETVhSYVdGSm9Xa2RHTUZsVFFqQmhXRkp6V2xRd2FWWkZZelpKUlVKcFlraFdiRmt5Um5KYVZqbDFXbGhTTTJJelNuSkphVUYwV1hwd01rbEhlSEJaYms0eVpFZEdNazFUUVhSalNFcHNZekpXTUVsRVdXZE1WMk5uVFdwUmQwbERNWHBKUkVWNVQwUkNORTU2U1hkSlF6RjNZVmhvWmxwdE1UQkpTR3d4WkdwUmVVMUlRV2RNV0U0eVpFZEdNazFUTVhkWldFcG9ZbGhOWjJSSVZuVmFWREI0VDIxYWNHSkhNSFJhTTBwb1lWYzBPVTFEUVhSWk0wcHRTVVJSTTBsRE1YTmlNbVJ6V2xoYWJHSkRRbXhqYmtwMlkybEJkRmw2Y0doSlIzaHdXVzA1ZDJSWVRXZE1WMFpxU1VSSloweFhSbWxKUkZGM1lYbEJkRmw2Y0hwSlIwNTJZMGhyWjJVeU9YZFlNbHB3WWtkV09VbERNVFVpTENKVVNGVk5RazVCU1V3aU9pSWlMQ0pCVlZSSVQxSWlPaUlpZlE9PQ==
      - name: Get segments
        id: get-segments
        run: |
          SEGMENTS=$(jq -c '.OUTPUT_FILES | keys' /app/data.json)
          echo "segments=$SEGMENTS" >> $GITHUB_OUTPUT
  encode:
    needs: download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        segment: ${{ fromJson(needs.download.outputs.segments) }}
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Encode segment
        run: |
          cd /app
          mkdir -p encoded
          python3 encode.py ${{ matrix.segment }}
      - name: Save encoded segment
        uses: actions/upload-artifact@v4
        with:
          name: segment-${{ matrix.segment }}
          path: /app/encoded
  upload:
    needs: encode
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Download all encoded segments
        uses: actions/download-artifact@v4
        with:
          pattern: segment-*
          path: /app/encoded
      - name: Extract necessary files and clean up
        run: |
          cd /app/encoded

          for dir in segment-*; do
            if [ -d "$dir" ]; then
              mv "$dir"/* .
              rmdir "$dir"
            fi
          done

          ls -sh
      - name: Merge and upload files
        run: |
          cd /app

          python3 upload.py
  delete:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: segment-*
