name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    outputs:
      segments: ${{ steps.get-segments.outputs.segments }}
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Cache files for download
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Run download script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWt0cGJtYzVPRGd4SWl3aVVrVlFUeUk2SW5WeVltRnVMVzlqZEc4dGMzVmpZMjkwWVhOb0lpd2lWRWRmUVZCSlgwbEVJam9pTVRZMU5EWXlOekFpTENKVVIxOUJVRWxmU0VGVFNDSTZJakZsTVdWbU1XSmlZalpsT0dNMlltTTVNREF5TURkallUVmhNVEZqWmpaaUlpd2lWRWRmUWs5VVgxUlBTMFZPSWpvaU56QXdPVGMwTlRFM01qcEJRVVZXVVZwdlNUTXlUM053UVVaMk1YWXhWVjlYUkRGT1gwcEVYMVJUTlhOaU5DSXNJa1pKVEVVaU9qTTBNeXdpUmtsTVJWOU9RVTFGSWpvaVcxTXdNUzB3T0YwZ1FtOW5kWE1nVTJ0cGJHd2dXekV3T0RCd1hTQmJVM1ZpWFNCQVFXNXBiV1Z6WDA5alpXRnVMbTFyZGlJc0lrbEVJam9pUW05blgyVmlZemMyUFRFOU1UQTRNSEFpTENKRFRVUWlPaUphYlZwMFkwZFdia2xETVhCSlNIUndZbXc1YldGWGVHeG1VMEYwV20xc2MyUkhWbmxZTWs1MllsaENjMXBZWjJkSmJWSjVXVmhrTUZwWWFEQlFWMXAyWW01U2JXRlhlR3hRVjJkMVpFaFNiVTl1VW14bFNGRTVTbmxDUVZGWE5YQmlWMVo2V0RBNWFscFhSblZKUTJNMldtMDVkV1JIVG5aaVJ6bDVVRmhrYjJGWVVteFBiVnAyWW01U2VtRlljR3hRVkUweVQyNW5PVTFVUVRabFZEQjRUVVJ3YkdKdFJtbGlSMVU1U2pKS2JHUklaR3hhVnpSdlpFTjNkMHhFVlhkTlEydHVUMjFHYzJOSGFHaFFVMlJ3V21sb2MyUkRhREJNUkZFMVQxTnJjMDFUZUhCYWFXaHpaRU5vTUV4RVZYZE5RMnR6UzBSRmRFdElVWFJPUkdzMVMxTnJkazFUZDNkTFUydHVTV2xCZEdKWFJuZEpSRUZuVEZjeGJHUkhSbXRaV0ZKb1QyNU5ObGxUUWpCaFdGSnpXbFF3YVZGRlJuVmhWekZzWXpFNVVGa3lWbWhpYVVsblRGY3hiR1JIUm10WldGSm9UMjVOTm1ONVFqQmhXRkp6V2xRd2FWRkZSblZoVnpGc1l6RTVVRmt5Vm1oaWFVbG5URmN4YkdSSFJtdFpXRkpvU1VoU2NHUkhlR3hRVTBwQlVWYzFjR0pYVm5wWU1EbHFXbGRHZFVscFFYUlplbkF5U1VkNGNGbHVUakprUjBZeVRWTkJkR05JU214ak1sWXdTVVJaWjB4WFkyZE5hbEYzU1VNeGVrbEVSVFZOYWtJMFRWUkJORTFEUVhSamFVRjZUVU5CZEdOSGJEUllNbHAwWkVOQ05XUllXVEJOYWtKM1NVTXhlbVJ1VW1oa2FrVjBZMGRHZVZsWE1YcEpTRkl4WW0xVk9VMVVjRzFoVjNoMFRGZGtlVmxYYkhWUVZFRm5URmRPZVZwcFFUQk9RMEYwWWtjNWJtSkhWakphVjNkbldsaEtlV0l6U1dkTVYwMDJXVk5DYzJGWFNuWmpTRlo2U1VNeGFGbDVRWGxKUXpGb1dXbEJNRTFIYzJkTVYwMDJZM2xDYW1JelFqVkpTSFIyWTBZNWJXRlhlR3htVTBGMFpWRTlQU0lzSWxSSVZVMUNUa0ZKVENJNklqRXpOQ0lzSWtGVlZFaFBVaUk2SWpZMk56STNOVEl4TnpjaWZRPT0=
      - name: Get segments
        id: get-segments
        run: |
          SEGMENTS=$(jq -c '.OUTPUT_FILES | keys' /app/data.json)
          echo "segments=$SEGMENTS" >> $GITHUB_OUTPUT
  encode:
    needs: download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        segment: ${{ fromJson(needs.download.outputs.segments) }}
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Encode segment
        run: |
          cd /app
          mkdir -p encoded
          python3 encode.py ${{ matrix.segment }}
      - name: Save encoded segment
        uses: actions/upload-artifact@v4
        with:
          name: segment-${{ matrix.segment }}
          path: /app/encoded
  upload:
    needs: encode
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Download all encoded segments
        uses: actions/download-artifact@v4
        with:
          pattern: segment-*
          path: /app/encoded
      - name: Extract necessary files and clean up
        run: |
          cd /app/encoded

          for dir in segment-*; do
            if [ -d "$dir" ]; then
              mv "$dir"/* .
              rmdir "$dir"
            fi
          done

          ls -sh
      - name: Merge and upload files
        run: |
          cd /app

          python3 upload.py
  delete:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: segment-*
