name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    outputs:
      segments: ${{ steps.get-segments.outputs.segments }}
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Cache files for download
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Run download script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWt0cGJtYzVPRGd4SWl3aVVrVlFUeUk2SW5WeVltRnVMVzlqZEc4dGMzVmpZMjkwWVhOb0lpd2lWRWRmUVZCSlgwbEVJam9pTVRZMU5EWXlOekFpTENKVVIxOUJVRWxmU0VGVFNDSTZJakZsTVdWbU1XSmlZalpsT0dNMlltTTVNREF5TURkallUVmhNVEZqWmpaaUlpd2lWRWRmUWs5VVgxUlBTMFZPSWpvaUlpd2lSa2xNUlNJNk5EQXNJa1pKVEVWZlRrRk5SU0k2SWx0VE1VVXlYU0JFWVc1a1lXUmhiaUJiTnpJd2NGMGdXMlIxWVd4ZElFQkJibWx0WlhOZlQyTmxZVzR1Yld0Mklpd2lTVVFpT2lKRVlXNWZZVFkyTnpBOU1UMDNNakJ3SWl3aVEwMUVJam9pV20xYWRHTkhWbTVKUXpGd1NVaDBjR0pzT1cxaFYzaHNabE5CZEZsNmNESkpSM2h3V1c1bmVVNXFWV2RNV0dkNVRtcFZkR05IUm5sWlZ6RjZTVWMxZGt4WGJIVmFiVGc1VFZOQmRHUnRXV2RKYlZKNVdWaGtNRnBZYURCUVYxcDJZbTVTYldGWGVHeFFWMmQxWkVoU2JVOXVVbXhsU0ZFNVNubENWVko1UVhSSlJVSnBZa2hXYkZreVJuSmFWamwxV2xoU00ySXpTbkpKUTJNMldtMDVkV1JIVG5aaVJ6bDVVRmhrYjJGWVVteFBiVnAyWW01U2VtRlljR3hRVkVrd1QyNW5PV1I1TVRCYVdHZ3dXRE5qZEUxcVFUWmxWREI0VFVSd2JHSnRSbWxpUjFVNVNqSktiR1JJWkd4YVZ6UnZaRU4zZDB4RVZYZE5RMnR1VDIxR2MyTkhhR2hRVTJSd1dtbG9jMlJEYURCTVJGRTFUMU5yYzAxVGVIQmFhV2h6WkVOb01FeEVWWGROUTJ0elMwUkZkRXRJVVhST1JHczFTMU5yZGsxVGQzZExVMnR1U1dsQmRHSlhSbmRKUkVGblRGY3hiR1JIUm10WldGSm9UMjVOTmxsVWIzZEpTRkp3WkVkNGJGQlRTbUpKUlVKQ1ltMXNkRnBZVG1aVU1rNXNXVmMwWjFoVFNXZE1WekZzWkVkR2ExbFlVbWhQYmswMlkzcHZkMGxJVW5Ca1IzaHNVRk5LWWtsRlFrSmliV3gwV2xoT1psUXlUbXhaVnpSbldGTkpaMHhYTVd4a1IwWnJXVmhTYUVsSVVuQmtSM2hzVUZOS1lrbEZRa0ppYld4MFdsaE9abFF5VG14WlZ6Um5XRk5CYVVsRE1XcGpiVmxuVFdwWloweFlRbkJsUmpsdFlsaFJaMlZZVmpKT1JFbDNZME5CZEdOcFFYbE5lVFExVG5wWloweFlUV2ROVkVrMFRVaG5NMDFxUVdkTVYzaDJXako0YkdSdFZuTkpSMVo1WTIwNWVVbERNWGRqYlZaNldsaFJaMk15ZUhaa2VVRjBXWHB3YUVsSGVIQlpiVGwzWkZoTloweFhSbXBKUkVsblRGZEpObGxUUVhwT1YzTm5URmROTm1ONVFtcGlNMEkxU1VoMGRtTkdPVzFoVjNoc1psTkJkR1ZSUFQwaWZRPT0=
      - name: Get segments
        id: get-segments
        run: |
          SEGMENTS=$(jq -c '.OUTPUT_FILES | keys' /app/data.json)
          echo "segments=$SEGMENTS" >> $GITHUB_OUTPUT
  encode:
    needs: download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        segment: ${{ fromJson(needs.download.outputs.segments) }}
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Encode segment
        run: |
          cd /app
          mkdir -p encoded
          python3 encode.py ${{ matrix.segment }}
      - name: Save encoded segment
        uses: actions/upload-artifact@v4
        with:
          name: segment-${{ matrix.segment }}
          path: /app/encoded
  upload:
    needs: encode
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Download all encoded segments
        uses: actions/download-artifact@v4
        with:
          pattern: segment-*
          path: /app/encoded
      - name: Extract necessary files and clean up
        run: |
          cd /app/encoded

          for dir in segment-*; do
            if [ -d "$dir" ]; then
              mv "$dir"/* .
              rmdir "$dir"
            fi
          done

          ls -sh
      - name: Merge and upload files
        run: |
          cd /app

          python3 upload.py
  delete:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: segment-*
